repository:
  name: coffeeprism.github.io
  description: Coffee Prism - Exploring the world of coffee
  homepage: https://www.coffeeprism.com
  private: false
  has_issues: true
  has_projects: false
  has_wiki: false
  is_template: false
  default_branch: main
  allow_squash_merge: true
  allow_merge_commit: true
  allow_rebase_merge: true
  delete_branch_on_merge: true
  topics: jekyll, coffee, blog

branches:
  - name: main
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks:
        strict: true
        contexts: ["github-pages"]
      enforce_admins: false
      restrictions: null

pages:
  source: 
    branch: gh-pages
    path: / 