title: Coffee Prism
description: Exploring the world of coffee through a prism of knowledge
url: https://www.coffeeprism.com
baseurl: ""
permalink: /:categories/:title/

# GitHub Pages settings
github: [metadata]
repository: CoffeePrism/coffeeprism.github.io

# Image settings
use_remote_images: true
remote_image_base_url: "https://source.unsplash.com/random/800x600/?"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  coffee:
    output: true
    permalink: /coffee/:path/
  equipment:
    output: true
    permalink: /equipment/:path/
  categories:
    output: true
    permalink: /categories/:path/
  tags:
    output: true
    permalink: /tags/:path/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "coffee"
    values:
      layout: "coffee"
  - scope:
      path: ""
      type: "equipment"
    values:
      layout: "equipment"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"

# Affiliate settings
affiliate:
  amazon:
    tracking_id: "coffeeprism-20"
    enabled: true
  
# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
  - LICENSE
  - CNAME
  - .github
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - .editorconfig 