title: Coffee Prism
description: Exploring the world of coffee through a prism of knowledge
url: https://coffeeprism.com
baseurl: ""
permalink: /:categories/:title/

# Image settings
use_remote_images: true
remote_image_base_url: "https://source.unsplash.com/featured/?"

# Build settings
markdown: kramdown
highlighter: rouge

# Collections
collections:
  coffee:
    output: true
    permalink: /coffee/:path/
  equipment:
    output: true
    permalink: /equipment/:path/
  categories:
    output: true
    permalink: /categories/:path/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "coffee"
    values:
      layout: "coffee"
  - scope:
      path: ""
      type: "equipment"
    values:
      layout: "equipment"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"

# Affiliate settings
affiliate:
  amazon:
    tracking_id: "coffeeprism-20"
    enabled: true
  
# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md 