title: Coffee Prism
description: Exploring the world of coffee through a prism of knowledge
url: https://www.coffeeprism.com
baseurl: ""
permalink: /:categories/:title/

# GitHub Pages settings
github: [metadata]
repository: CoffeePrism/coffeeprism.github.io
domain: coffeeprism.com
url: "https://www.coffeeprism.com"
baseurl: ""
enforce_ssl: "www.coffeeprism.com"
safe: true
lsi: false
incremental: false

# Language settings
languages: ["en"]
default_lang: "en"
exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico", "assets"]

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Amazon Affiliate settings
affiliate:
  amazon:
    tracking_id: "coffeeprism-20"
    enabled: true

# Image settings
use_remote_images: false
default_image: "/assets/images/coffee-default.jpg"
default_category_images:
  coffee-knowledge: "/assets/images/categories/coffee-science.jpg"
  brewing: "/assets/images/categories/brewing.jpg"
  roasting: "/assets/images/categories/roasting.jpg"
  beans: "/assets/images/categories/beans.jpg"
  equipment: "/assets/images/coffee-cup.jpg"
  latte-art: "/assets/images/categories/latte-art.jpg"
  barista-skills: "/assets/images/categories/barista.jpg"

# Default image collection (for random selection)
default_images:
  - "/assets/images/coffee-default.jpg"
  - "/assets/images/coffee-beans-default.jpg"
  - "/assets/images/coffee-beans.jpg"
  - "/assets/images/coffee-cup.jpg"
use_random_default_images: true
use_smart_images: true

# Image fallback settings
image_fallback_strategy:
  - featured_image
  - category_image
  - default_image

# Collections
collections:
  coffee:
    output: true
    permalink: /:collection/:name/
  equipment:
    output: true
    permalink: /:collection/:name/
  categories:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      lang: "en"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "coffee"
    values:
      layout: "coffee"
  - scope:
      path: ""
      type: "equipment"
    values:
      layout: "equipment"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
  - LICENSE
  - CNAME
  - .github
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - .editorconfig
  - _tags 