title: Coffee Prism
description: Exploring the world of coffee through a prism of knowledge
url: https://www.coffeeprism.com
baseurl: ""
permalink: /:categories/:title/

# GitHub Pages settings
github: [metadata]
repository: CoffeePrism/coffeeprism.github.io
safe: true
lsi: false
incremental: false

# 多语言支持配置
languages: ["zh", "en"]
default_lang: "zh"
exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico", "assets"]

# 其他 GitHub Pages 相关配置
domain: coffeeprism.com
url: "https://www.coffeeprism.com"
enforce_ssl: "www.coffeeprism.com"

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Amazon Affiliate settings
affiliate:
  amazon:
    tracking_id: "coffeeprism-20"
    enabled: true

# Image settings
use_remote_images: false
default_image: "/assets/images/coffee-default.jpg"
default_coffee_image: "/assets/images/coffee-beans-default.jpg"
remote_image_base_url: "https://images.unsplash.com/photo-"
# 默认图片集合（用于随机选择）
default_images:
  - "/assets/images/defaults/coffee-default-1.jpg"
  - "/assets/images/defaults/coffee-default-2.jpg"
  - "/assets/images/defaults/coffee-default-3.jpg"
  - "/assets/images/defaults/coffee-default-4.jpg"
  - "/assets/images/defaults/coffee-default-5.jpg"
  - "/assets/images/defaults/coffee-default-6.jpg"
  - "/assets/images/defaults/coffee-default-7.jpg"
  - "/assets/images/defaults/coffee-default-8.jpg"
  - "/assets/images/defaults/coffee-default-9.jpg"
  - "/assets/images/defaults/coffee-default-10.jpg"
use_random_default_images: true

# Collections
collections:
  coffee:
    output: true
    permalink: /:collection/:name/
  equipment:
    output: true
    permalink: /:collection/:name/
  categories:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      lang: "zh"
  - scope:
      path: "en"
    values:
      lang: "en"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "coffee"
    values:
      layout: "coffee"
  - scope:
      path: ""
      type: "equipment"
    values:
      layout: "equipment"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
  - LICENSE
  - CNAME
  - .github
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - .editorconfig
  - _tags

# Image display and processing
use_smart_images: true 