title: Coffee Prism
description: Exploring the world of coffee through a prism of knowledge
url: https://www.coffeeprism.com
baseurl: ""
permalink: /:categories/:title/

# GitHub Pages settings
github: [metadata]
repository: CoffeePrism/coffeeprism.github.io
domain: coffeeprism.com
url: "https://www.coffeeprism.com"
baseurl: ""
enforce_ssl: "www.coffeeprism.com"
safe: true
lsi: false
incremental: false

# Language settings
languages: ["en"]
default_lang: "en"
exclude_from_localizations: ["javascript", "images", "css", "scripts", "favicon.ico", "assets"]

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Amazon Affiliate settings
affiliate:
  amazon:
    tracking_id: "coffeeprism-20"
    enabled: true

# Image settings
use_remote_images: false
default_image: "/assets/images/coffee-default.jpg"

# Category-specific images
default_category_images:
  coffee-knowledge: "/assets/images/categories-extra/coffee-science.jpg"
  brewing: "/assets/images/categories/brewing.jpg"
  roasting: "/assets/images/categories/coffee-equipment.jpg"
  beans: "/assets/images/categories/beans.jpg"
  equipment: "/assets/images/categories/coffee-equipment.jpg"
  latte-art: "/assets/images/categories/latte-art.jpg"
  barista-skills: "/assets/images/categories-extra/barista.jpg"
  coffee-culture: "/assets/images/categories/coffee-culture.jpg"
  coffee-history: "/assets/images/categories/coffee-history.jpg"
  reviews: "/assets/images/categories-extra/coffee-cups.jpg"
  guides: "/assets/images/categories-extra/brewing-guide.jpg"

# Default image collection for random selection
default_images:
  # Category images
  - "/assets/images/categories/brewing.jpg"
  - "/assets/images/categories/espresso.jpg"
  - "/assets/images/categories/coffee-brewing-methods.jpg"
  - "/assets/images/categories/coffee-beans-closeup.jpg"
  - "/assets/images/categories/coffee-pour-over.jpg"
  - "/assets/images/categories/coffee-drink.jpg"
  - "/assets/images/categories/coffee-culture.jpg"
  - "/assets/images/categories/coffee-history.jpg"
  - "/assets/images/categories/coffee-equipment.jpg"
  # Extra category images
  - "/assets/images/categories-extra/coffee-science.jpg"
  - "/assets/images/categories-extra/coffee-cups.jpg"
  - "/assets/images/categories-extra/coffee-beans-roasted.jpg"
  - "/assets/images/categories-extra/french-press.jpg"
  - "/assets/images/categories-extra/coffee-packaging.jpg"
  - "/assets/images/categories-extra/coffee-shop.jpg"
  - "/assets/images/categories-extra/barista.jpg"
  - "/assets/images/categories-extra/brewing-guide.jpg"

use_random_default_images: true
use_smart_images: true

# Image fallback settings
image_fallback_strategy:
  - featured_image
  - category_image
  - default_image

# Collections
collections:
  coffee:
    output: true
    permalink: /:collection/:name/
  equipment:
    output: true
    permalink: /:collection/:name/
  categories:
    output: true
    permalink: /:collection/:name/

# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
      lang: "en"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "coffee"
    values:
      layout: "coffee"
  - scope:
      path: ""
      type: "equipment"
    values:
      layout: "equipment"
  - scope:
      path: ""
      type: "categories"
    values:
      layout: "category"

# Pagination
paginate: 10
paginate_path: "/page/:num/"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md
  - LICENSE
  - CNAME
  - .github
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - .editorconfig
  - _tags 