baseURL = "https://www.coffeeprism.com/"
languageCode = "zh-cn"
title = "Coffee Prism"
theme = "Mainroad"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[Author]
  name = "Coffee Prism"
  bio = "专业的咖啡爱好者网站，提供咖啡豆介绍、冲泡方式和咖啡装备评测"

[Params]
  description = "专业的咖啡爱好者网站，提供咖啡豆介绍、冲泡方式和咖啡装备评测"
  copyright = "Coffee Prism"
  readmore = true
  authorbox = true
  toc = true
  pager = true
  post_meta = ["author", "date", "categories", "tags"]
  mainSections = ["posts"]
  dateformat = "2006-01-02"
  opengraph = true
  schema = true
  twitter_cards = true

  [Params.style.vars]

  [Params.logo]
    title = "Coffee Prism"
    subtitle = "您的咖啡专业指南"

  [Params.thumbnail]
    visibility = ["list", "post"]

  [Params.sidebar]
    home = "right"
    list = "right"
    single = "right"
    widgets = ["search", "recent", "categories", "taglist", "social"]

  [Params.widgets]
    recent_num = 5
    categories_counter = true
    tags_counter = true

  [Params.widgets.social]

[[menu.main]]
identifier = "categories"
name = "分类"
url = "/categories/"
weight = 10

[[menu.main]]
identifier = "tags"
name = "标签"
url = "/tags/"
weight = 20

[[menu.main]]
identifier = "coffee-beans"
name = "咖啡豆种类"
url = "/coffee-beans/"
weight = 30

[[menu.main]]
identifier = "brewing-methods"
name = "冲泡方式"
url = "/brewing-methods/"
weight = 40

[[menu.main]]
identifier = "coffee-equipment"
name = "咖啡产品"
url = "/coffee-equipment/"
weight = 50

[[menu.main]]
identifier = "about"
name = "关于我们"
url = "/about/"
weight = 60

[[menu.main]]
identifier = "contact"
name = "联系我们"
url = "/contact/"
weight = 70

[outputs]
home = ["HTML", "RSS"]

# 添加新的分页配置
[pagination]
  pagerSize = 10
