# Coffee Grinders
coffee_grinder:
  - name: "Timemore 栗子C2 手动咖啡研磨机"
    description: "高精度手动咖啡研磨机，采用不锈钢刀盘，38mm锥形刀研磨均匀，适合各种咖啡冲泡方式。"
    image: "/assets/images/products/timemore-c2.jpg"
    price: "¥299"
    amazon_id: "B083FC3X5P"

# Pour Over Kits
pour_over_kit:
  - name: "Hario V60 滴滤式咖啡套装"
    description: "包含V60陶瓷滴滤杯、玻璃咖啡壶、滤纸和量勺，是手冲咖啡的完美入门套装。"
    image: "/assets/images/products/hario-v60-kit.jpg"
    price: "¥259"
    amazon_id: "B00JJIOJ7E"

# Coffee Beans
coffee_beans:
  - name: "埃塞俄比亚耶加雪菲G1精品咖啡豆"
    description: "来自埃塞俄比亚耶加雪菲产区的精品咖啡豆，中浅烘焙，具有明亮的柑橘酸和花香。"
    image: "/assets/images/products/yirgacheffe-beans.jpg"
    price: "¥89"
    amazon_id: "B086WLLPJ7"

# Yirgacheffe Coffee
yirgacheffe_coffee:
  - name: "埃塞俄比亚耶加雪菲精品咖啡豆 250g"
    description: "精选埃塞俄比亚耶加雪菲产区的精品咖啡豆，水洗处理，中浅烘焙，风味清新明亮。"
    image: "/assets/images/products/yirgacheffe-coffee.jpg"
    price: "¥98"
    amazon_id: "B07LFYX6TX"

# Coffee Drippers
coffee_dripper:
  - name: "Hario V60 02 陶瓷滴滤杯"
    description: "日本制造的经典滴滤杯，螺旋纹理设计有助于均匀萃取，适合1-4人份咖啡冲泡。"
    image: "/assets/images/products/hario-v60-dripper.jpg"
    price: "¥129"
    amazon_id: "B000P4D5HG"

# Moka Pots
moka_pot:
  - name: "Bialetti Moka Express 6杯摩卡壶"
    description: "意大利原装进口的经典摩卡壶，铝制八角形设计，能够制作出浓郁醇厚的意式咖啡。"
    image: "/assets/images/products/bialetti-moka.jpg"
    price: "¥249"
    amazon_id: "B00004RFRU"

# French Press
french_press:
  - name: "Bodum Chambord 法压壶 1000ml"
    description: "经典设计的法压壶，不锈钢框架和耐热玻璃，制作简单，能够保留咖啡的油脂和风味。"
    image: "/assets/images/products/bodum-french-press.jpg"
    price: "¥299"
    amazon_id: "B00008XEWG"

# Espresso Machines
espresso_machine:
  - name: "德龙 Dedica EC685 家用半自动意式浓缩咖啡机"
    description: "紧凑型半自动咖啡机，15巴压力，带有专业蒸汽管，可制作浓缩咖啡和奶泡。"
    image: "/assets/images/products/delonghi-dedica.jpg"
    price: "¥1599"
    amazon_id: "B00KHO0CYW"

# Coffee Scales
coffee_scale:
  - name: "Timemore 黑镜咖啡秤"
    description: "高精度咖啡秤，0.1g精确度，内置计时器，防水设计，适合精准控制咖啡冲泡。"
    image: "/assets/images/products/timemore-scale.jpg"
    price: "¥239"
    amazon_id: "B07XY15TRK"

# Kettles
kettle:
  - name: "Hario V60 细口手冲壶 1.2L"
    description: "不锈钢细口手冲壶，精确控制水流，带温度计，适合手冲咖啡的精准注水。"
    image: "/assets/images/products/hario-kettle.jpg"
    price: "¥329"
    amazon_id: "B000IGOXLS" 