name: 自动文章生成与发布

on:
  schedule:
    # 每天凌晨2点（UTC时间，根据需要调整）
    - cron: '0 18 * * *'
  workflow_dispatch:  # 允许手动触发

# 设置权限
permissions:
  contents: write
  pages: write
  id-token: write

# 允许一个并发部署
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # 生成文章并构建页面
  generate-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: 设置Python环境
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'

      - name: 安装Python依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 设置Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: 配置Git
        run: |
          git config --global user.name "自动发布机器人"
          git config --global user.email "autobot@coffeeprism.com"

      - name: 创建备份目录
        run: |
          mkdir -p backups/$(date +%Y%m%d)
          cp -r content backups/$(date +%Y%m%d)/ || echo "没有content目录可备份"

      - name: 生成文章
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        run: python scripts/generate_and_publish.py

      - name: 构建网站
        run: hugo --minify

      - name: 提交并推送到main分支
        run: |
          # 添加内容目录的更改
          git add content
          
          # 强制添加public目录（被.gitignore忽略）
          git add -f public
          
          # 检查是否有更改需要提交
          if [[ -z $(git status -s) ]]; then
            echo "没有需要提交的更改"
            exit 0
          fi
          
          git commit -m "自动发布: 添加新文章 - $(date +%Y-%m-%d)"
          git push origin main

      # 添加缺少的上传工件依赖
      - name: 上传工件
        uses: actions/upload-artifact@v2
        with:
          name: github-pages
          path: ./public
          if-no-files-found: error

      - name: 上传页面工件
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

  # 部署到GitHub Pages
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: generate-and-build
    steps:
      - name: 部署到GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2 