name: Build and deploy Jekyll site with custom plugins

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0'
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle config set --local path 'vendor/bundle'
          bundle install

      - name: Build Jekyll site
        env:
          JEKYLL_ENV: production
        run: |
          bundle exec jekyll build --verbose
          ls -la _site

      - name: Deploy to GitHub Pages
        if: success() && github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: _site
          branch: gh-pages
          clean: true
          single-commit: true 