name: Daily Coffee Article Publisher

on:
  schedule:
    - cron: '0 2 * * *'  # 每天UTC 2点运行（北京时间10点）
  workflow_dispatch:     # 允许手动触发
  push:
    branches:
      - main            # 当推送到main分支时也会触发

jobs:
  publish_article:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: true  # 获取所有子模块，包括Hugo主题

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests python-slugify

      - name: Generate Article
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        run: |
          mkdir -p scripts
          python scripts/generate_and_publish.py

      - name: Build Site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Publish daily coffee article' 